# -*- coding: utf-8 -*-
"""Assignment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-St_OSbKnWZylSQJA2RlRPW8CFvwXWf-
"""

def solve(string):
  output = {}
  for i in string:
    keys = output.keys()
    if i not in keys:
      output[i]=1
    else:
        output[i]+=1

  return output
print(solve(input()))

""